import { Container, Typography } from '@mui/material';
import Box from '@mui/material/Box';
import FormControl from '@mui/material/FormControl';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { years } from '../helpers';

const Home: NextPage = () => {
  const [selectedYear, setSelectedYear] = useState<string>(years[0]);
  // const { results, isLoading, isError } = useResults(year);

  const handleChange = (event: SelectChangeEvent) => {
    setSelectedYear(event.target.value);
  };

  return (
    <div>
      <Head>
        <title>Resultados do Campeonato Brasileiro</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container maxWidth='md'>
          <Typography
            marginTop='20px'
            marginBottom='30px'
            textAlign='center'
            variant='h4'
            component='div'
          >
            Resultados do Campeonato Brasileiro
          </Typography>
          <Box sx={{ minWidth: 120 }} textAlign='center'>
            <FormControl>
              <InputLabel id='year-select-label'>Ano</InputLabel>
              <Select
                labelId='year-select-label'
                id='year-select'
                value={selectedYear}
                label='Ano'
                onChange={handleChange}
              >
                {years.map((year) => (
                  <MenuItem key={year} value={year}>
                    {year}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
        </Container>
      </main>
    </div>
  );
};

export default Home;
